name: algebra_expressions
description: Algebraic expressions.
version: 1.0.0
repository: https://github.com/jimmyl0l3c/algebra_expressions

environment:
  sdk: ^3.5.3

dependencies:
  big_fraction: ^6.0.0
  collection: ^1.17.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
